---
version: "3.4"

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - 8081:15672
    networks:
      - rabbitmq_net

  origin:
    container_name: 'origin'
    build:
      context: orig/
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASS=rabbit
      - PUB_TOPIC=compse140.o
    networks:
      - rabbitmq_net
    depends_on:
      - rabbitmq

  intermediate:
    container_name: 'intermediate'
    build:
      context: imed/
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASS=rabbit
      - PUB_TOPIC=compse140.i
      - SUB_TOPIC=compse140.o
    networks:
      - rabbitmq_net
    depends_on:
      - rabbitmq

#  observer:
#    container_name: 'observer'
#    build:
#      context: obse/
#    environment:
#      - RABBITMQ_HOST=rabbitmq
#      - RABBITMQ_USER=rabbit
#      - RABBITMQ_PASS=rabbit
#      - SUB_TOPIC_1=compse140.o
#      - SUB_TOPIC_2=compse140.i
#    volumes:
#      - ./data/:/opt/data/
#    networks:
#      - rabbitmq_net
#    depends_on:
#      - rabbitmq

  httpserver:
    container_name: 'httpserver'
    build:
      context: httpserv/
    ports:
      - 8080:80
    volumes: 
      - ./data/:/usr/share/nginx/html/
    depends_on:
      - rabbitmq

networks:
  rabbitmq_net:
    name: rabbitmq_net
    driver: bridge
  
