---
version: "3.4"

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - 8081:15672
    networks:
      - rabbitmq_net

  orig:
    container_name: 'orig'
    build:
      context: orig/
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASS=rabbit
    networks:
      - rabbitmq_net
    depends_on:
      - rabbitmq

  imed:
    container_name: 'imed'
    build:
      context: imed/
    networks:
      - rabbitmq_net
    depends_on:
      - rabbitmq

  obse:
    container_name: 'obse'
    build:
      context: obse/
    volumes:
      - ./data:/opt/data
    networks:
      - rabbitmq_net
    depends_on:
      - rabbitmq

  httpserv:
    container_name: 'httpserv'
    build:
      context: httpserv/
    ports:
      - 8080:80
    volumes: 
      - ./data:/opt/data
    depends_on:
      - rabbitmq

networks:
  rabbitmq_net:
    name: rabbitmq_net
    driver: bridge
  